### ISSUE TITLE
Can't pass options.

### ISSUE THREAD

**Issue by ababba15** [3stack-software/meteor-blaze-chosen#1]
Hi! First of all thanks for this pretty nice package.

Just can't pass options like it is demonstrated in README. Am I doing it wrong way?

```
{{#chosen max_shown_results=2}}
  <select name="location__add_district" id="location__add_district" class="chosen-select">
    {{# each locations}}
      <option value="{{_id}}">{{name}}</option>
    {{/each}}
  </select>
{{/chosen}}
```

**Comment by nathan-muir** [comment]
Hey @ababba15,

You're doing it right, however we're currently using version 1.4.2 of chosen.js; the option [`max_shown_results` was added in 1.5.0](https://github.com/harvesthq/chosen/releases/tag/v1.5.0)
